Fresh start 2
Mamut3D/guocci pull request #6
Opened 2016-11-01 15:07 UTC by Mamut3D

Code is kinda shitty after moth delay of project.
Travis added + tests

2016-11-14 10:51 UTC, amarthadan requested changes
I didn't really go through the tests, hopefully @arax will :smile:

2016-11-14 10:51 UTC, amarthadan commented on app/models/appliances.rb
> +      next unless service
It's faster to call `compact` before the `collect` than skipping the elements with `next`. I actually did the benchmark because I was curious :sunglasses:

2016-11-14 10:51 UTC, Misenko commented on lib/utils/appdb_reader.rb
> +        response.success? ? parse_appdb_response(response.parsed_response) : nil
Do you differentiate between unsuccessful response (`nil`) and empty response (empty array)? Because if not you can skip this check altogather.

2016-11-14 10:51 UTC, Misenko commented on lib/utils/appdb_reader.rb
> +          voname = occi_image['vo']['name']
If there is no `name` key it will return `nil` but the default you set in the `else` branch is an empty string. Wouldn't that cause problems?

2016-11-14 10:51 UTC, Misenko commented on lib/utils/appdb_reader.rb
> +          image_id = occi_image['id'].split('os_tpl#')[1]
What if there is no second element in that array? :dog:

2016-11-15 09:22 UTC, Mamut3D commented on app/models/appliances.rb
> +      next unless service
update code with compact

2016-11-15 09:25 UTC, Mamut3D commented on lib/utils/appdb_reader.rb
> +        response.success? ? parse_appdb_response(response.parsed_response) : nil
Not relevant, nil means there was an error. Empty response can be generated as from parse_appdb_response function

2016-11-15 09:29 UTC, Mamut3D commented on lib/utils/appdb_reader.rb
> +          voname = occi_image['vo']['name']
It definitely might, but "standard" for appdb response describes, that it cannot happen - if you know which standard i mean ;-). Same comment can be used for multiple fields.

2016-11-15 09:30 UTC, Mamut3D commented on lib/utils/appdb_reader.rb
> +          image_id = occi_image['id'].split('os_tpl#')[1]
It definitely might, but "standard" for appdb response describes, that it cannot happen - if you know which standard i mean ;-). Same comment can and will be used for multiple fields.

2016-11-15 10:45 UTC, amarthadan approved these changes

2016-11-15 10:48 UTC, merged