Devel branch
Mamut3D/guocci pull request #8
Opened 2017-01-02 09:02 UTC by Mamut3D

Pull contains:
 * Route instances - added getter methods
 * Readme - removed defaul bs, added travis logo
 * Added forked dependencies to rOCCI-core/api

2017-01-04 09:10 UTC, amarthadan requested changes

2017-01-04 09:10 UTC, amarthadan commented on app/controllers/v1/test_occi_controller.rb
> +module V1
What is this for? If it's just for testing purposes it has no place in `master` branch.

2017-01-04 09:10 UTC, amarthadan commented on app/models/base.rb
> +    @client ||= Occi::Api::Client::ClientHttp.new(endpoint: endpoint,
Not sure how you're using this but isn't it possible that you will call `occi_client` with one endpoint, which will create new client and then with another endpoint but it will return the same client with an old endpoint set?

2017-01-04 09:10 UTC, amarthadan commented on app/models/instances.rb
> +  def all_test_method(service_id, cert)
Again, if you need this it should go to a different branch, `master` should contain only production ready code :smirk:

2017-01-04 09:10 UTC, Misenko commented on app/models/instances.rb
> +    compute.mixins.find { |mixin| mixin.scheme == 'http://fedcloud.egi.eu/occi/compute/flavour/1.0#' }
I would say this is not correct. I think this should look similar to the `appliance_mixin` method, shouldn't it?

2017-01-04 09:10 UTC, Misenko commented on config/routes.rb
>      resources :test_appdb, only: [:index]
Both of these should go.

2017-01-04 10:24 UTC, Mamut3D commented on app/models/base.rb
> +    @client ||= Occi::Api::Client::ClientHttp.new(endpoint: endpoint,
It is a workaround for now, client is created separatelly for each contoroller call. Will be reworked in future

2017-01-04 10:24 UTC, Mamut3D commented on app/models/instances.rb
> +  def all_test_method(service_id, cert)
removed

2017-01-04 10:24 UTC, Mamut3D commented on app/models/instances.rb
> +    compute.mixins.find { |mixin| mixin.scheme == 'http://fedcloud.egi.eu/occi/compute/flavour/1.0#' }
Nope, it does not have separate class like OsTpl

2017-01-04 10:25 UTC, Mamut3D commented on config/routes.rb
>      resources :test_appdb, only: [:index]
Went to hell

2017-01-04 10:25 UTC, Mamut3D commented on app/controllers/v1/test_occi_controller.rb
> +module V1
Went to hell

2017-01-04 15:00 UTC, Misenko commented on config/routes.rb
>      resources :test_appdb, only: [:index]
I meant these lines from this file :smile:

2017-01-05 13:02 UTC, amarthadan approved these changes

2017-01-05 13:15 UTC, merged